### ISSUE TITLE
max-length: 120 seems to be too long for JSX

### ISSUE THREAD

**Issue by xcarpentier** [cooperka/eslint-config-cooperka#1]
Hello Kevin,

```javascript
return <Image source={{ uri: this.props.user.avatar }} style={[styles.avatarStyle, this.props.avatarStyle]} />;
```

https://github.com/cooperka/eslint-config-cooperka/blob/55d135da2aa55f802a95bf91209de2cb0f85eea2/index.js#L30

Regarding the integration into react-native-gifted-chat of your eslint configuration is that possible to change it here? 

Or if not change it here:

https://github.com/FaridSafi/react-native-gifted-chat/blob/86046e3e6f35b1e3c03f306e6ec27e0de333c481/.eslintrc#L7

For me, I think,  **80** or max **100** should be good... (this is the sizes I'm using many times)

(I'm using prettier-eslint + format on save and it's annoying everytime I save it)

Regards,

**Comment by cooperka** [comment]
Absolutely, if you just add a custom rule you can override any configs from this library.

Personally, I don't like enforcing mandatory line lengths, and I don't use `prettier` so I've never dealt with the issue you describe. I would choose to format that line as follows:

```jsx
return (
  <Image
    source={{ uri: this.props.user.avatar }}
    style={[styles.avatarStyle, this.props.avatarStyle]}
  />
);
```

Perhaps it's possible to disable certain formatting features of `prettier`?

**Comment by cooperka** [comment]
Closing as it's not actionable, but feel free to continue the conversation here.
